/* ===== chart ===== */
function candle(a,n,ma){CHD=n;const r=rng(hs(a.id)+n.length+9),w=640,h=250,ch=200,N=n.length,bw=w/N,Q=ohlc(a,n),O=Q?Q.O:n.map((c,i)=>i?n[i-1]:c*(1-a.vol*.2)),H=Q?Q.H:n.map((c,i)=>Math.max(c,O[i])*(1+r()*a.vol*.5)),L=Q?Q.L:n.map((c,i)=>Math.min(c,O[i])*(1-r()*a.vol*.5)),V=Q?Q.V:n.map(()=>.3+r()),mn=Math.min(...L),mx=Math.max(...H),y=v=>ch-6-(v-mn)/(mx-mn||1)*(ch-14),vm=Math.max(...V);
 const avg=k=>n.map((_,i)=>i<k-1?null:n.slice(i-k+1,i+1).reduce((x,z)=>x+z,0)/k);
 const pl=(arr,o,d)=>{const P=arr.map((v,i)=>v==null?null:[(i+.5)*bw,y(v)]).filter(Boolean);return P.length?`<path d="${P.map((q,i)=>(i?'L':'M')+q[0].toFixed(1)+' '+q[1].toFixed(1)).join('')}" fill="none" stroke="var(--ink)" stroke-width="1.4" opacity="${o}" ${d?'stroke-dasharray="4 3"':''}/>`:''};
 return`<svg viewBox="0 0 ${w} ${h}" id="ch" onpointermove="tip(event)" onpointerleave="document.getElementById('tt').textContent=''">${n.map((c,i)=>{const col=c>=O[i]?'var(--up)':'var(--dn)',x=(i+.5)*bw;return`<line x1="${x}" x2="${x}" y1="${y(H[i])}" y2="${y(L[i])}" stroke="${col}"/><rect x="${x-bw*.3}" width="${bw*.6}" y="${y(Math.max(c,O[i]))}" height="${Math.max(1,Math.abs(y(c)-y(O[i])))}" fill="${col}"/><rect x="${x-bw*.3}" width="${bw*.6}" y="${h-V[i]/vm*40}" height="${V[i]/vm*40}" fill="var(--faint)" opacity=".35"/>`}).join('')}${ma?pl(avg(5),.9,0)+pl(avg(20),.5,1):''}</svg>`}
function bars(V,Lb,sel,ck){const w=640,h=150,mx=Math.max(...V,1),bw=w/V.length;return`<svg viewBox="0 0 ${w} ${h}">${V.map((v,i)=>{const bh=v/mx*(h-44),x=i*bw+bw*.2;return`<rect x="${x}" y="${h-24-bh}" width="${bw*.6}" height="${Math.max(bh,2)}" rx="6" fill="var(--ink)" opacity="${i===sel?1:.18}" ${ck?`style="cursor:pointer" onclick="smo=${i-V.length+1};render()"`:''}/><text x="${i*bw+bw/2}" y="${h-6}" text-anchor="middle" font-size="12" fill="var(--faint)">${Lb[i]}</text><text x="${i*bw+bw/2}" y="${h-28-bh}" text-anchor="middle" font-size="11" fill="var(--soft)">${v?Math.round(v):''}</text>`}).join('')}</svg>`}
function donut(L,sz=160,sw=22){const r=(sz-sw)/2,c=2*Math.PI*r,T=L.reduce((x,y)=>x+y.v,0)||1;let o=0;return`<svg viewBox="0 0 ${sz} ${sz}" style="width:${sz}px;height:${sz}px;margin:0 auto">${L.map(x=>{const l=x.v/T*c,g=Math.min(2,l*.06),d=`<circle cx="${sz/2}" cy="${sz/2}" r="${r}" fill="none" style="stroke:${x.c};cursor:pointer" stroke-width="${sw}" stroke-dasharray="${Math.max(l-g,0)} ${c}" stroke-dashoffset="${-o}" transform="rotate(-90 ${sz/2} ${sz/2})" onclick="pfk=pfk==='${x.k}'?'':'${x.k}';render()"/>`;o+=l;return d}).join('')}</svg>`}
function line(pts,w=640,h=200){CHD=pts;if(pts.length<2)return'';const mn=Math.min(...pts),mx=Math.max(...pts),r=mx-mn||1;
 const P=pts.map((v,i)=>[i/(pts.length-1)*w,h-8-(v-mn)/r*(h-24)]);const d=P.map((p,i)=>(i?'L':'M')+p[0].toFixed(1)+' '+p[1].toFixed(1)).join('');
 const c=pts[pts.length-1]>=pts[0]?'var(--up)':'var(--dn)';
 return`<svg viewBox="0 0 ${w} ${h}" id="ch" onpointermove="tip(event)" onpointerleave="document.getElementById('tt').textContent=''"><defs><linearGradient id="g" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="${c}" stop-opacity=".16"/><stop offset="1" stop-color="${c}" stop-opacity="0"/></linearGradient></defs><path d="${d}L${w} ${h}L0 ${h}Z" fill="url(#g)"/><path d="${d}" fill="none" stroke="${c}" stroke-width="2.2" stroke-linejoin="round" pathLength="1" stroke-dasharray="1" style="animation:dr .9s var(--e)"/></svg><style>@keyframes dr{from{stroke-dashoffset:1}to{stroke-dashoffset:0}}</style>`}
function tip(e){const r=e.currentTarget.getBoundingClientRect(),i=Math.max(0,Math.min(CHD.length-1,Math.round((e.clientX-r.left)/r.width*(CHD.length-1))));document.getElementById('tt').textContent=CHL[i]+' · '+CHF(CHD[i])}
