/* ===== stock detail (mock fundamentals/history: replace series()/info() with API data) ===== */
function rng(s){return()=>{s|=0;s=s+0x6D2B79F5|0;let t=Math.imul(s^s>>>15,1|s);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
const hs=x=>[...x].reduce((h,c)=>Math.imul(h^c.charCodeAt(0),16777619),2166136261)>>>0;
function series(a,days){const r=rng(hs(a.id)+days),n=days===1?48:60,v=a.vol*Math.sqrt(Math.max(days,.4)/n)*1.6,o=[1];let x=1;for(let i=1;i<n;i++){x*=1+(r()-.48)*v*2;o.push(x)}const k=a.p/o[n-1];return o.map(y=>y*k)}
function info(a){const r=rng(hs(a.id)),PER=8+r()*30,mg=.08+r()*.17,rev0=20+r()*280;return{PER,PBR:.8+r()*8,ROE:5+r()*25,EPS:a.p/PER,DIV:r()*3,DEBT:30+r()*120,PSR:PER*mg*.8,mg,rev0,cap:rev0*PER*mg*.8,vol:Math.round((.5+r())*(a.k==='kr'?9e6:5e7))}}
const pf=(a,x)=>a.usd?'$'+(x/FX).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}):won(x);
const cp=x=>x>=1e12?(x/1e12).toFixed(1)+'조':x>=1e8?Math.round(x/1e8)+'억':Math.round(x/1e4)+'만';
const DESC={PER:'주가가 기업의 이익에 비해 어느 정도 수준인지 보여주는 지표. 낮을수록 이익 대비 저평가일 수 있습니다.',PBR:'주가를 1주당 순자산으로 나눈 값. 1배 미만이면 장부상 자산보다 싸게 거래된다는 뜻입니다.',PSR:'시가총액을 매출로 나눈 값. 아직 이익이 작은 성장 기업을 볼 때 쓰입니다.',EPS:'1주당 순이익. 기업이 주식 한 주당 얼마를 벌었는지 보여줍니다.',ROE:'자기자본으로 얼마나 이익을 냈는지 보여주는 수익성 지표입니다.',영업이익률:'매출에서 영업이익이 차지하는 비율. 본업의 수익성을 보여줍니다.',부채비율:'자본 대비 부채의 비율. 높을수록 재무 부담이 큽니다.',배당수익률:'주가 대비 1년 배당금의 비율. 보유만 해도 받을 수 있는 수익률입니다.'};
function metric(k){sheet(`<div style="font-weight:700;font-size:18px">${k}</div><div class="sub" style="margin:10px 0 20px;line-height:1.7">${DESC[k]}</div><button class="btn s w" onclick="closeM()">닫기</button>`)}
function openDetail(id){dsel=id;tab='detail';render();scrollTo(0,0)}
function dhead(a){const c=(a.p/a.o-1)*100;return`<div class="big" style="font-size:32px">${pf(a,a.p)}</div><div class="${cl(c)}" style="font-weight:600">${c>=0?'▲ ':'▼ '}${pf(a,Math.abs(a.p-a.o))} (${pc(c)})</div>`}
function finView(a,I){let r=rng(hs(a.id)+7),q=fp==='q',L=q?['25 Q1','25 Q2','25 Q3','25 Q4']:['2022','2023','2024','2025'],d=q?4:1,u=a.usd?'$B':'조 원',ni0=I.rev0*I.mg*.8;
 let D=L.map((_,i)=>{const rev=I.rev0*(1+.07*i+(r()-.5)*.08)/d,opm=I.mg+(r()-.5)*.03,op=rev*opm,ni=op*.8,ta=I.rev0*(1.6+.1*i+r()*.1),td=ta*(.3+I.DEBT/400);return{rev,op,ni,opm,npm:ni/rev,eps:I.EPS*ni/ni0,ta,td,eq:ta-td,cash:ta*.12,ca:ta*.35,opcf:ni*1.25,inv:-rev*.12,fin:-rev*.05,fcf:ni*1.25-rev*.1}});const RF=realFin(a);if(RF){L=RF.L;D=RF.D;u=RF.u}
 const T={is:[['매출','rev'],['영업이익','op'],['순이익','ni'],['EPS','eps','p'],['영업이익률','opm','%'],['순이익률','npm','%']],bs:[['총자산','ta'],['총부채','td'],['자본','eq'],['현금','cash'],['유동자산','ca']],cf:[['영업활동','opcf'],['투자활동','inv'],['재무활동','fin'],['잉여현금흐름','fcf']]}[ft];
 const f=(x,t)=>x==null||isNaN(x)?'—':t==='%'?(x*100).toFixed(1)+'%':t==='p'?pf(a,x):x.toFixed(1);
 return`<div class="lab">재무제표 <span style="font-weight:400">(단위: ${u} · ${RF?'실제 데이터 · 제공되지 않는 항목은 —':'시뮬레이션'})</span></div><div class="card"><div class="seg" style="margin-top:0">${[['is','손익계산서'],['bs','재무상태표'],['cf','현금흐름표']].map(([k,l])=>`<button class="${ft===k?'on':''}" onclick="ft='${k}';render()">${l}</button>`).join('')}</div><div class="seg" style="margin-top:0">${[['y','연간'],['q','분기']].map(([k,l])=>`<button class="${fp===k?'on':''}" onclick="fp='${k}';render()">${l}</button>`).join('')}</div>
 <div style="overflow-x:auto"><table style="width:100%;border-collapse:collapse;font-size:13px"><tr style="color:var(--faint)"><td></td>${L.map(x=>`<td style="text-align:right;padding:6px 0 6px 12px">${x}</td>`).join('')}</tr>${T.map(([n,k,t])=>`<tr style="border-top:1px solid var(--bd)"><td style="padding:10px 0;white-space:nowrap">${n}</td>${D.map(x=>`<td style="text-align:right;padding-left:12px;font-weight:600;white-space:nowrap">${f(x[k],t)}</td>`).join('')}</tr>`).join('')}</table></div></div>`}
function detailView(){const a=A(dsel),I=info(a),h=S.hold[a.id],eq=a.k==='kr'||a.k==='us',st=eq||a.k==='etf',n=series(a,dper),yr=series(a,365),lo=Math.min(...yr,a.p),hi=Math.max(...yr,a.p),now=Date.now();
 CHL=chl(a,n,dper,now);CHF=x=>pf(a,x);
 const R=a.real,hiD=R?R.hv:Math.max(a.o,a.p)*(1+a.vol*.15),loD=R?R.lv:Math.min(a.o,a.p)*(1-a.vol*.15);
 const stats=st?[['시가',pf(a,R?R.o:a.o)],['고가',pf(a,hiD)],['저가',pf(a,loD)],['거래량',I.vol.toLocaleString('ko-KR')],['거래대금','₩'+cp(R&&R.amt?R.amt:I.vol*a.p)],...(eq?[['시가총액',a.usd?'$'+(I.cap*1.5).toFixed(0)+'B':I.cap.toFixed(0)+'조 원']]:[])]:[];
 const mt=eq?[['PER',I.PER.toFixed(1)+'배'],['PBR',I.PBR.toFixed(2)+'배'],['PSR',I.PSR.toFixed(2)+'배'],['EPS',pf(a,I.EPS)],['ROE',I.ROE.toFixed(1)+'%'],['영업이익률',(I.mg*100).toFixed(1)+'%'],['부채비율',I.DEBT.toFixed(0)+'%'],['배당수익률',I.DIV.toFixed(2)+'%']]:a.k==='etf'?[['배당수익률',I.DIV.toFixed(2)+'%']]:[];
 return`<div class="sub" style="cursor:pointer;margin-bottom:14px" onclick="tab='market';render()">‹ 시장</div><div style="font-weight:700;font-size:20px">${a.n}</div><div class="sub" style="margin-bottom:10px">${KIND[a.k]} · ${a.id}${a.usd?' · USD/KRW '+FX:''}</div><div id="dh">${dhead(a)}</div>
 <div class="card" style="margin-top:16px;padding:14px 14px 10px"><div class="seg" style="margin:0 0 6px">${[[1,'1일'],[7,'1주'],[30,'1개월'],[90,'3개월'],[180,'6개월'],[365,'1년'],[1825,'5년']].map(([v,l])=>`<button class="${dper===v?'on':''}" onclick="dper=${v};render()">${l}</button>`).join('')}</div><div class="sub" id="tt" style="height:20px"></div>${ctype==='c'?candle(a,n,ma):line(n)}<div class="seg" style="margin:8px 0 0">${[['l','선'],['c','캔들']].map(([k,l])=>`<button class="${ctype===k?'on':''}" onclick="ctype='${k}';render()">${l}</button>`).join('')}<button class="${ma?'on':''}" onclick="ma=!ma;ctype='c';render()">이동평균</button></div></div>
 <div class="card" style="margin-top:12px"><div class="sub" style="display:flex;justify-content:space-between"><span>52주 최저 ${pf(a,lo)}</span><span>최고 ${pf(a,hi)}</span></div><div class="bar" style="margin-top:8px"><div style="width:${(a.p-lo)/(hi-lo||1)*100}%;background:var(--ink)"></div></div></div>
 <div class="grid g2" style="margin-top:12px"><button class="btn w" onclick="openTrade('${a.id}')">매수</button><button class="btn s w" onclick="openTrade('${a.id}');setSide('sell')">매도${h?' · 보유 '+(+h.q.toFixed(4)):''}</button></div>
 ${stats.length?`<div class="lab">시세 정보</div><div class="grid">${stats.map(([l,v])=>`<div class="card stat"><div class="sub">${l}</div><div class="v" style="font-size:16px">${v}</div></div>`).join('')}</div>`:''}
 ${mt.length?`<div class="lab">투자 지표 <span style="font-weight:400">· 눌러서 설명 보기 · 시뮬레이션</span></div><div class="card">${mt.map(([l,v])=>`<div class="row tap" onclick="metric('${l}')"><span>${l}</span><b>${v}</b></div>`).join('')}</div>`:''}
 ${eq?finView(a,I):''}`}
