/* ===== news / indicators / alerts (sample data: swap NEWS & econList() for APIs) ===== */
function note(t){S.notes.unshift({t:Date.now(),m:t});S.notes.length=Math.min(S.notes.length,30);toast(t)}
function alerts(){const d=new Date().toDateString();Object.keys(S.hold).forEach(id=>{const a=A(id),c=a.p/a.o-1,k=id+(c>0?'u':'d');if(Math.abs(c)>.03&&S.al[k]!==d){S.al[k]=d;note(a.n+' '+pc(c*100)+(c>0?' 급등':' 급락'))}});if(total()>=S.start*1.1&&!S.al.goal){S.al.goal=1;note('목표 자산 달성: 초기 자산 대비 +10%')}}
function ntView(){return`<div class="lab">알림</div><div class="card">${S.notes.slice(0,5).map(n=>`<div class="row"><span>${n.m}</span><span class="sub">${new Date(n.t).toLocaleDateString('ko-KR')}</span></div>`).join('')||'<div class="sub">새 알림이 없습니다</div>'}</div>`}
function mkTabs(){return`<div class="seg" style="margin-top:0">${[['stocks','종목'],['news','뉴스'],['econ','경제지표']].map(([k,l])=>`<button class="${mt===k?'on':''}" onclick="mt='${k}';render()">${l}</button>`).join('')}</div>`}
const NEWS=[['한국 증시','코스피, 외국인 순매수에 반도체주 중심 상승 마감','005930',1],['한국 증시','SK하이닉스, 고대역폭 메모리 수요 확대 기대감','000660',3],['한국 증시','현대차, 북미 하이브리드 판매 증가세','005380',5],['미국 증시','나스닥, 빅테크 실적 앞두고 강보합','AAPL',2],['미국 증시','엔비디아, AI 서버 수요에 장중 신고가 근접','NVDA',4],['미국 증시','테슬라, 로보택시 일정 발표에 변동성 확대','TSLA',6],['경제','소비자물가 상승률 둔화 흐름 이어져',null,7],['경제','수출 증가율 반도체 중심으로 개선',null,9],['금리','연준 위원들 금리 인하 속도 신중론',null,8],['금리','한국은행, 기준금리 동결 기조 유지 전망',null,12],['환율','원/달러 환율, 달러 강세 속 높은 수준 유지',null,2],['원자재','국제 금값, 안전자산 선호에 강세','GOLD',3],['원자재','은 가격, 산업 수요 기대에 상승','SILVER',10],['코인','비트코인, ETF 자금 유입에 상승세','BTC',1],['코인','이더리움, 네트워크 업그레이드 앞두고 관심 증가','ETH',5]];
function pageNews(){const C=['전체','내 포트폴리오','한국 증시','미국 증시','경제','금리','환율','원자재','코인'],L=NEWS.map((n,i)=>({n,i})).filter(({n})=>nc==='전체'||(nc==='내 포트폴리오'?n[2]&&S.hold[n[2]]:n[0]===nc));
 return`<h1>시장</h1>${mkTabs()}<div class="seg" style="margin-top:0">${C.map(c=>`<button style="flex:1 1 auto;padding:7px 8px" class="${nc===c?'on':''}" onclick="nc='${c}';render()">${c}</button>`).join('')}</div><div class="sub" style="margin:0 2px 10px">${NREAL?'Google 뉴스 헤드라인 · 눌러서 원문 보기':'샘플 헤드라인입니다. 프록시를 연결하면 실제 기사가 표시됩니다.'}</div><div class="card">${L.map(({n,i})=>`<div class="row tap" onclick="openNews(${i})"><div><b>${n[1]}</b><div class="sub">${n[0]} · ${n[3]}시간 전</div></div></div>`).join('')||'<div class="sub">해당하는 뉴스가 없습니다</div>'}</div>`}
function openNews(i){const n=NEWS[i];sheet(`<div class="sub">${n[0]} · ${n[3]}시간 전</div><div style="font-weight:700;font-size:18px;margin:6px 0 12px;line-height:1.4">${n[1]}</div><div class="sub" style="line-height:1.7;margin-bottom:18px">샘플 기사입니다. 뉴스 API 연결 시 이 자리에서 원문 링크로 이동합니다.</div>${n[2]?`<button class="btn w" onclick="closeM();openDetail('${n[2]}')">관련 종목 보기</button>`:`<button class="btn s w" onclick="closeM()">닫기</button>`}`)}
function econList(){return[{n:'KOSPI',p:2650,vol:.008,u:'n'},{n:'KOSDAQ',p:850,vol:.011,u:'n'},{n:'S&P 500',p:5700,vol:.007,u:'n'},{n:'NASDAQ',p:18000,vol:.01,u:'n'},{n:'Dow Jones',p:42000,vol:.006,u:'n'},{n:'USD/KRW',p:FX,vol:.004,u:'n'},{n:'WTI 국제유가',p:72,vol:.015,u:'$'},{n:'금 (1g)',p:A('GOLD').p,vol:.006,u:'w'},{n:'미국 국채 10Y',p:4.1,vol:.012,u:'%'},{n:'VIX',p:16,vol:.04,u:'n'},{n:'한국 기준금리',p:2.5,vol:0,u:'%'},{n:'미국 기준금리',p:4.25,vol:0,u:'%'},{n:'CPI (YoY)',p:2.4,vol:0,u:'%'}].map(e=>({...e,id:e.n}))}
const fe=(e,x)=>e.u==='%'?x.toFixed(2)+'%':e.u==='$'?'$'+x.toFixed(2):e.u==='w'?won(x):x.toLocaleString('ko-KR',{maximumFractionDigits:2});
const dts=(n,d)=>Array.from({length:n},(_,i)=>new Date(Date.now()-(n-1-i)/(n-1)*d*DAY).toLocaleDateString('ko-KR'));
function spark(P){const mn=Math.min(...P),mx=Math.max(...P),r=mx-mn||1,d=P.map((v,i)=>(i?'L':'M')+(i/(P.length-1)*80).toFixed(1)+' '+(26-(v-mn)/r*24).toFixed(1)).join('');return`<svg viewBox="0 0 80 28" style="width:80px;height:28px"><path d="${d}" fill="none" stroke="var(--ink)" stroke-width="1.6" stroke-linejoin="round" opacity=".7"/></svg>`}
function pageEcon(){return`<h1>시장</h1>${mkTabs()}<div class="sub" style="margin:0 2px 10px">${Object.keys(ES).length?'지수·유가·VIX·국채금리·환율·금은 실시간 · 한국 기준금리만 고정 샘플값':'샘플 수치입니다.'} 눌러서 추이를 볼 수 있습니다.</div><div class="card">${econList().map((e,i)=>{const P=series(e,7),c=e.vol?(P[P.length-1]/P[0]-1)*100:null;return`<div class="row tap" onclick="econSheet(${i})"><div><b>${e.n}</b><div class="sub ${c==null?'':cl(c)}">${c==null?'—':pc(c)}</div></div><div style="display:flex;align-items:center;gap:14px">${e.vol?spark(P):''}<b style="min-width:84px;text-align:right">${fe(e,e.p)}</b></div></div>`}).join('')}</div>`}
function econSheet(i){const e=econList()[i],P=series(e,30);CHL=dts(P.length,30);CHF=x=>fe(e,x);sheet(`<div style="font-weight:700;font-size:18px">${e.n}</div><div class="big" style="font-size:28px;margin:4px 0 10px">${fe(e,e.p)}</div><div class="sub" id="tt" style="height:20px"></div>${e.vol?line(P):'<div class="sub" style="margin:10px 0 6px">변동이 거의 없는 지표입니다.</div>'}<button class="btn s w" style="margin-top:16px" onclick="closeM()">닫기</button>`)}
