/* ===== allocation plan / new simulation ===== */
const PL=['현금','주식','ETF','채권','금','은','비트코인','예비자금'];
function planView(by,T){const P=S.plan,g=k=>by[k]||0,rows=[['현금',g('현금'),P[0]+P[7]],['주식',g('한국 주식')+g('미국 주식'),P[1]],['ETF',g('ETF'),P[2]],['채권',g('채권'),P[3]],['금',g('금'),P[4]],['은',g('은'),P[5]],['코인',g('코인'),P[6]]];
 return`<div class="lab" style="display:flex;justify-content:space-between;align-items:center">목표 배분 대비<button class="btn s" style="padding:6px 14px;font-size:13px" onclick="editPlan()">수정</button></div><div class="card">${rows.map(([n,v,t])=>`<div class="row"><span>${n}</span><span><b>${(v/T*100).toFixed(1)}%</b> <span class="sub">목표 ${t}%</span></span></div>`).join('')}</div>`}
let nd='normal';
const dinfo=k=>{const Q=DIFF[k],mx=Math.max(...Q.tiers.map(t=>t[1]));return[['시작 금액',won(Q.start)],['시간당 급여',won(Q.wage)],['공부 보너스','최대 +'+Math.round(mx*100)+'%'],['게임 승리 확률','×'+Q.odds.toFixed(2)],['거래 수수료','0.015%']].map(([l,v])=>`<div class="row" style="padding:5px 0;border:0"><span class="sub">${l}</span><b>${v}</b></div>`).join('')};
function pickDiff(k){nd=k;document.querySelectorAll('#dseg button').forEach(b=>b.classList.toggle('on',b.dataset.k===k));document.getElementById('dinfo').innerHTML=dinfo(k)}
const xbtn='<button aria-label="닫기" onclick="closeM()" style="flex:none;width:32px;height:32px;border:0;border-radius:50%;background:var(--bg2);color:var(--ink);font:inherit;font-size:15px;cursor:pointer">✕</button>';
const shead=(t,x)=>`<div style="display:flex;justify-content:space-between;align-items:center;gap:12px"><div style="font-weight:700;font-size:18px">${t}</div>${x?xbtn:''}</div>`;
const pinputs=v=>PL.map((n,i)=>`<div><div class="sub">${n}</div><input class="pp" type="number" inputmode="numeric" min="0" value="${v[i]}" oninput="psum()"></div>`).join('');
function newSim(first){nd=S.diff||'normal';sheet(`${shead(first===true?'시작 설정':'새 시뮬레이션',first!==true)}<div class="sub" style="margin:4px 0 12px;line-height:1.6">${first===true?'난이도와 목표 자산 배분을 정해 주세요. 목표 배분은 나중에 자산 탭에서 언제든 수정할 수 있습니다.':'초기 자금은 전액 현금으로 지급되고 배분은 투자 목표로 저장됩니다. 현재 기록은 삭제됩니다.'}</div><div class="sub">난이도</div><div class="seg" id="dseg" style="margin:6px 0 4px">${DIFF_ORDER.map(k=>`<button data-k="${k}" class="${nd===k?'on':''}" onclick="pickDiff('${k}')">${DIFF[k].n}</button>`).join('')}</div><div id="dinfo">${dinfo(nd)}</div><div class="sub" style="margin:12px 0 6px">목표 배분 (%)</div><div class="grid g2" style="gap:8px">${pinputs(S.plan)}</div><div id="ps" class="sub" style="margin:12px 0"></div><button class="btn w" id="pg" onclick="startSim()">시작하기</button>${first===true?'':'<button class="btn s w" style="margin-top:10px" onclick="closeM()">취소</button>'}`,first===true);psum()}
function psum(){const t=[...document.querySelectorAll('.pp')].reduce((x,e)=>x+(+e.value||0),0),ps=document.getElementById('ps'),pg=document.getElementById('pg');if(ps)ps.innerHTML='합계 <b'+(t===100?'':' class="rise"')+'>'+t+'%</b>';if(pg)pg.disabled=t!==100}
function startSim(){const Q=DIFF[nd],a=Q.start;const plan=[...document.querySelectorAll('.pp')].map(e=>Math.max(0,+e.value||0)),o=S,n=Date.now();
 S={cash:a,wage:Q.wage,fee:FEE,tiers:Q.tiers.map(x=>x.slice()),diff:nd,hold:{},tx:[{t:n,ty:'etc',m:'초기 자금 지급',a}],study:[],hist:[{t:n-DAY,v:a},{t:n,v:a}],start:a,realized:0,theme:o.theme,bank:[],notes:[],al:{},gm:0,plan,custom:o.custom||[],bondSeries:o.bondSeries||[],bshift:0,onb:1};save();closeM();tab='home';render()}
/* 시뮬레이션을 새로 시작하지 않고 목표 배분만 수정 */
function editPlan(){sheet(`${shead('목표 배분 수정',true)}<div class="sub" style="margin:4px 0 12px;line-height:1.6">보유 자산과 기록은 그대로 두고 목표 비율만 바꿉니다. 합계는 100%여야 합니다.</div><div class="grid g2" style="gap:8px">${pinputs(S.plan)}</div><div id="ps" class="sub" style="margin:12px 0"></div><button class="btn w" id="pg" onclick="savePlan()">저장</button><button class="btn s w" style="margin-top:10px" onclick="closeM()">취소</button>`);psum()}
function savePlan(){S.plan=[...document.querySelectorAll('.pp')].map(e=>Math.max(0,+e.value||0));save();closeM();render();toast('목표 배분이 저장되었습니다')}
