/* ===== views ===== */
const inM=(t,o)=>{const d=new Date(t),n=new Date(),k=new Date(n.getFullYear(),n.getMonth()+o,1);return d.getFullYear()===k.getFullYear()&&d.getMonth()===k.getMonth()};
const ST=(o=0)=>{const m=S.study.filter(s=>inM(s.t,o)),b=m.reduce((x,s)=>x+s.base,0),n=m.reduce((x,s)=>x+s.bonus,0);return{sec:m.reduce((x,s)=>x+s.sec,0),base:b,bonus:n,inc:b+n}};
const V={detail(){return detailView()},game(){return gameView()},
home(){const T=total(),H=S.hist,prev=H.length?H[H.length-1].v:T,d=T-(H.slice().reverse().find(h=>!sameDay(h.t,Date.now()))||H[0]).v,td=S.study.filter(s=>sameDay(s.t,Date.now()));
 const ts=td.reduce((x,s)=>x+s.sec,0)+elapsed(),ti=td.reduce((x,s)=>x+s.base+s.bonus,0),pl=holdVal()-cost(),ret=(T/S.start-1)*100,m=ST();
 return`<h1>STUDY & INVEST</h1><div class="sub">총자산</div><div class="big" id="tot">${won(T)}</div><div class="${cl(d)}" style="font-weight:600">${sg(d)} (${pc(d/(T-d)*100)})</div>
 <div class="card" style="margin-top:18px;padding:14px 14px 10px"><div class="seg" style="margin:0 0 6px">${[[7,'1주'],[30,'1개월'],[90,'3개월'],[180,'6개월'],[365,'1년'],[1e5,'전체']].map(([n,l])=>`<button style="flex:1 1 auto;padding:7px 8px" class="${period===n?'on':''}" onclick="period=${n};render()">${l}</button>`).join('')}</div><div class="sub" id="tt" style="height:20px"></div>${(CHL=histP().map(x=>new Date(x.t).toLocaleDateString('ko-KR')),CHF=won,line(histP().map(x=>x.v)))}</div>
 <div class="lab">오늘</div><div class="grid"><div class="card stat"><div class="sub">오늘 공부</div><div class="v">${hm(ts)}</div></div><div class="card stat"><div class="sub">오늘 번 돈</div><div class="v">${won(ti)}</div></div><div class="card stat"><div class="sub">이번 달 공부</div><div class="v">${hm(m.sec)}</div></div><div class="card stat"><div class="sub">보유 현금</div><div class="v">${won(S.cash)}</div></div><div class="card stat"><div class="sub">평가손익</div><div class="v ${cl(pl)}">${sg(pl)}</div></div><div class="card stat"><div class="sub">전체 수익률</div><div class="v ${cl(ret)}">${pc(ret)}</div></div><div class="card stat"><div class="sub">이번 달 급여</div><div class="v">${won(m.inc)}</div></div><div class="card stat"><div class="sub">이번 달 투자수익</div>${(()=>{const k=new Date(),ms=(S.hist.find(h=>h.t>=+new Date(k.getFullYear(),k.getMonth(),1))||S.hist[0]).v,x=T-ms-m.inc-(window.lvMonth?lvMonth():0);return`<div class="v ${cl(x)}">${sg(x)}</div>`})()}</div></div>`},
study(){const m=ST(smo),rows=S.study.filter(x=>inM(x.t,smo)).reverse(),n0=new Date(),md=new Date(n0.getFullYear(),n0.getMonth()+smo,1),O=[-5,-4,-3,-2,-1,0];
 return`<h1>공부</h1><div class="card"><div class="timer" id="tm">${clock(elapsed())}</div><button class="btn w" onclick="toggleTimer()">${run?'STOP':'START'}</button></div>
 <div class="lab" style="display:flex;justify-content:space-between;align-items:center"><span style="cursor:pointer;padding:4px 12px" onclick="smo--;render()">‹</span><span>${md.getFullYear()}년 ${md.getMonth()+1}월</span><span style="cursor:pointer;padding:4px 12px;${smo>=0?'opacity:.25;pointer-events:none':''}" onclick="smo++;render()">›</span></div>
 <div class="grid g2"><div class="card stat"><div class="sub">총 공부시간</div><div class="v">${hm(m.sec)}</div></div><div class="card stat"><div class="sub">총 수입</div><div class="v">${won(m.inc)}</div></div><div class="card stat"><div class="sub">총 기본급</div><div class="v">${won(m.base)}</div></div><div class="card stat"><div class="sub">총 보너스</div><div class="v">${won(m.bonus)}</div></div></div>
 <div class="lab">월별 공부시간 <span style="font-weight:400">· 시간</span></div><div class="card">${bars(O.map(o=>ST(o).sec/3600),O.map(o=>new Date(n0.getFullYear(),n0.getMonth()+o,1).getMonth()+1+'월'),smo+5,true)}</div>
 <div class="lab">공부 기록</div><div class="card">${rows.map(s=>`<div class="row"><div><b>${new Date(s.t).toLocaleDateString('ko-KR')}</b><div class="sub">${hm(s.sec)} · 기본 ${won(s.base)} · 보너스 ${won(s.bonus)}</div></div><b>${sg(s.base+s.bonus)}</b></div>`).join('')||'<div class="sub">기록이 없습니다</div>'}</div>`},
market(){if(mt==='news')return pageNews();if(mt==='econ')return pageEcon();return`<h1>시장</h1>${mkTabs()}<input placeholder="종목명 또는 티커 검색 (예: 삼성, NVDA)" oninput="q=this.value;list()" value="${q}"><div class="sub" style="margin:10px 2px">USD/KRW ${FX.toFixed(2)} · ${API?'검색하면 모든 종목을 추가할 수 있습니다':'가격은 시뮬레이션 데이터입니다'}</div><div id="ml"></div>`},
portfolio(){const T=total(),G=T+loanBal(),by={'현금':S.cash};Object.entries(S.hold).forEach(([id,h])=>{const k=KIND[A(id).k]||'기타';by[k]=(by[k]||0)+h.q*price(id)});S.bank.forEach(b=>{const k=b.ty==='dep'?'예금':'적금';by[k]=(by[k]||0)+bankPrin(b)});
 by['기타']=by['기타']||0;const sh=['#111','#444','#777','#999','#bbb','#d4d4d4','#e8e8e8'],e=Object.entries(by).sort((a,b)=>b[1]-a[1]);const pl=holdVal()-cost();
 return`<h1>포트폴리오</h1><div class="big">${won(T)}</div><div style="margin:16px 0">${donut(e.map(([k,v],i)=>({k,v,c:`color-mix(in srgb,var(--ink) ${Math.max(14,100-i*15)}%,var(--bg))`})))}</div>
 <div class="card">${e.map(([k,v])=>`<div class="row tap" onclick="pfk=pfk==='${k}'?'':'${k}';render()"><span style="${pfk===k?'font-weight:700':''}">${k}</span><span><b>${won(v)}</b> <span class="sub">${(v/G*100).toFixed(1)}%</span></span></div>`).join('')}${loanBal()>0?`<div class="row"><span>대출 (차감)</span><b class="dn">-${won(loanBal())}</b></div>`:''}</div>
 ${planView(by,G)}<div class="lab">보유 종목${pfk?' · '+pfk:''}</div><div class="card">${Object.entries(S.hold).filter(([id])=>!pfk||(KIND[A(id).k]||'기타')===pfk).map(([id,h])=>{const a=A(id),r=(a.p/h.c-1)*100;return`<div class="row tap" onclick="openDetail('${id}')"><div><b>${a.n}</b><div class="sub">${+h.q.toFixed(4)}개 · 평단 ${won(h.c)}</div></div><div style="text-align:right"><b>${won(h.q*a.p)}</b><div class="${cl(r)}" style="font-size:13px">${sg((a.p-h.c)*h.q)} (${pc(r)})</div></div></div>`}).join('')||'<div class="sub">보유 종목이 없습니다. 시장에서 매수해보세요.</div>'}</div>
 <div class="lab">손익</div><div class="grid g2"><div class="card stat"><div class="sub">미실현손익</div><div class="v ${cl(pl)}">${sg(pl)}</div></div><div class="card stat"><div class="sub">실현손익</div><div class="v ${cl(S.realized)}">${sg(S.realized)}</div></div></div><div class="grid g2" style="margin-top:12px">${[['배당금',S.tx.filter(t=>t.ty==='div').reduce((x,t)=>x+t.a,0)],['이자수익',S.tx.filter(t=>t.ty==='interest').reduce((x,t)=>x+t.a,0)]].map(([l,v])=>`<div class="card stat"><div class="sub">${l}</div><div class="v" style="font-size:16px">${sg(v)}</div></div>`).join('')}</div>`},
tx(){const F=[['all','전체'],['study','공부급여'],['stock','주식'],['etf','ETF'],['bond','채권'],['gold','금'],['silver','은'],['coin','코인'],['dep','예금'],['sav','적금'],['div','배당'],['interest','이자'],['living','생활비'],['loan','대출'],['etc','기타']];
 const KN=['study','kr','us','etf','bond','gold','silver','coin','bank','div','interest','living','loan','loanint'],TF={loan:t=>t.ty==='loan'||t.ty==='loanint',stock:t=>t.ty==='kr'||t.ty==='us',dep:t=>t.ty==='bank'&&/^예금/.test(t.m),sav:t=>t.ty==='bank'&&/^적금/.test(t.m),etc:t=>!KN.includes(t.ty)},
 rows=S.tx.filter(t=>flt==='all'||(TF[flt]?TF[flt](t):t.ty===flt));
 return`<h1>거래내역</h1><div class="seg">${F.map(([k,l])=>`<button style="flex:1 1 auto;padding:7px 8px" class="${flt===k?'on':''}" onclick="flt='${k}';render()">${l}</button>`).join('')}</div><div class="card">${rows.map(t=>`<div class="row"><div><b>${t.m}</b><div class="sub">${new Date(t.t).toLocaleDateString('ko-KR')}</div></div><b class="${cl(t.a)}">${sg(t.a)}</b></div>`).join('')||'<div class="sub">내역이 없습니다</div>'}</div>`},
more(){const st=ST();return`<h1>더보기</h1>${ntView()}${bankView()}${monthView()}${diffCard()}<div class="lab">게임</div><div class="card tap" onclick="tab='game';render();scrollTo(0,0)"><b>미니게임</b><div class="sub">게임머니로만 즐기는 가상 게임 · 실제 자산과 분리</div></div><div class="lab">화면</div><div class="seg">${[['','시스템'],['light','라이트'],['dark','다크']].map(([k,l])=>`<button class="${S.theme===k?'on':''}" onclick="S.theme='${k}';theme();save();render()">${l}</button>`).join('')}</div>
 ${statsView()}<button class="btn w" style="margin-top:22px" onclick="newSim()">새 시뮬레이션 시작 (자산 배분 설정)</button><button class="btn s w" style="margin-top:10px" onclick="if(confirm('모든 기록을 지우고 현재 난이도의 시작 금액으로 처음부터 시작할까요?')){const cu=S.custom,bs=S.bondSeries,sh=S.bshift;S=demo(S.diff);S.onb=1;S.custom=cu||[];S.bondSeries=bs||[];S.bshift=0;save();render()}">시뮬레이션 초기화</button>`}};
let ctype='l',ma=false,smo=0,sp=30,pfk='',gbet=10000,gres='',gcoin='h',gdice=3,grl='r',mt='stocks',nc='전체',q='',flt='all',CHD=[],CHL=[],CHF=n=>won(n),dsel=null,dper=30,ft='is',fp='y';
