/* ===== views ===== */
const inM=(t,o)=>{const d=new Date(t),n=new Date(),k=new Date(n.getFullYear(),n.getMonth()+o,1);return d.getFullYear()===k.getFullYear()&&d.getMonth()===k.getMonth()};
const ST=(o=0)=>{const m=S.study.filter(s=>inM(s.t,o)),b=m.reduce((x,s)=>x+s.base,0),n=m.reduce((x,s)=>x+s.bonus,0);return{sec:m.reduce((x,s)=>x+s.sec,0),base:b,bonus:n,inc:b+n}};
const V={detail(){return detailView()},game(){return gameView()},
home(){const T=total(),H=S.hist,prev=H.length?H[H.length-1].v:T,d=T-S.hist[Math.max(0,H.length-2)].v,td=S.study.filter(s=>sameDay(s.t,Date.now()));
 const ts=td.reduce((x,s)=>x+s.sec,0)+elapsed(),ti=td.reduce((x,s)=>x+s.base+s.bonus,0),pl=holdVal()-cost(),ret=(T/S.start-1)*100,m=ST();
 return`<h1>STUDY & INVEST</h1><div class="sub">총자산</div><div class="big" id="tot">${won(T)}</div><div class="${cl(d)}" style="font-weight:600">${sg(d)} (${pc(d/(T-d)*100)})</div>
 <div class="card" style="margin-top:18px;padding:14px 14px 10px"><div class="seg" style="margin:0 0 6px">${[[7,'1주'],[30,'1개월'],[60,'3개월'],[400,'전체']].map(([n,l])=>`<button class="${period===n?'on':''}" onclick="period=${n};render()">${l}</button>`).join('')}</div><div class="sub" id="tt" style="height:20px"></div>${(CHL=S.hist.slice(-period).map(x=>new Date(x.t).toLocaleDateString('ko-KR')),CHF=won,line(S.hist.slice(-period).map(x=>x.v)))}</div>
 <div class="lab">오늘</div><div class="grid"><div class="card stat"><div class="sub">오늘 공부</div><div class="v">${hm(ts)}</div></div><div class="card stat"><div class="sub">오늘 번 돈</div><div class="v">${won(ti)}</div></div><div class="card stat"><div class="sub">이번 달 공부</div><div class="v">${hm(m.sec)}</div></div><div class="card stat"><div class="sub">보유 현금</div><div class="v">${won(S.cash)}</div></div><div class="card stat"><div class="sub">평가손익</div><div class="v ${cl(pl)}">${sg(pl)}</div></div><div class="card stat"><div class="sub">전체 수익률</div><div class="v ${cl(ret)}">${pc(ret)}</div></div><div class="card stat"><div class="sub">이번 달 급여</div><div class="v">${won(m.inc)}</div></div><div class="card stat"><div class="sub">이번 달 투자수익</div>${(()=>{const k=new Date(),ms=(S.hist.find(h=>h.t>=+new Date(k.getFullYear(),k.getMonth(),1))||S.hist[0]).v,x=T-ms-m.inc;return`<div class="v ${cl(x)}">${sg(x)}</div>`})()}</div></div>`},
study(){const m=ST(smo),rows=S.study.filter(x=>inM(x.t,smo)).reverse(),n0=new Date(),md=new Date(n0.getFullYear(),n0.getMonth()+smo,1),O=[-5,-4,-3,-2,-1,0];
 return`<h1>공부</h1><div class="card"><div class="timer" id="tm">${clock(elapsed())}</div><button class="btn w" onclick="toggleTimer()">${run?'STOP':'START'}</button>
 <label class="sub" style="display:flex;gap:8px;margin-top:14px;align-items:center;justify-content:center"><input type="checkbox" style="width:auto" ${acc?'checked':''} onchange="acc=this.checked"> 체험용 600배속 (1초 = 10분)</label></div>
 <div class="lab" style="display:flex;justify-content:space-between;align-items:center"><span style="cursor:pointer;padding:4px 12px" onclick="smo--;render()">‹</span><span>${md.getFullYear()}년 ${md.getMonth()+1}월</span><span style="cursor:pointer;padding:4px 12px;${smo>=0?'opacity:.25;pointer-events:none':''}" onclick="smo++;render()">›</span></div>
 <div class="grid g2"><div class="card stat"><div class="sub">총 공부시간</div><div class="v">${hm(m.sec)}</div></div><div class="card stat"><div class="sub">총 수입</div><div class="v">${won(m.inc)}</div></div><div class="card stat"><div class="sub">총 기본급</div><div class="v">${won(m.base)}</div></div><div class="card stat"><div class="sub">총 보너스</div><div class="v">${won(m.bonus)}</div></div></div>
 <div class="lab">월별 공부시간 <span style="font-weight:400">· 시간</span></div><div class="card">${bars(O.map(o=>ST(o).sec/3600),O.map(o=>new Date(n0.getFullYear(),n0.getMonth()+o,1).getMonth()+1+'월'),smo+5,true)}</div>
 <div class="lab">공부 기록</div><div class="card">${rows.map(s=>`<div class="row"><div><b>${new Date(s.t).toLocaleDateString('ko-KR')}</b><div class="sub">${hm(s.sec)} · 기본 ${won(s.base)} · 보너스 ${won(s.bonus)}</div></div><b>${sg(s.base+s.bonus)}</b></div>`).join('')||'<div class="sub">기록이 없습니다</div>'}</div>`},
market(){if(mt==='news')return pageNews();if(mt==='econ')return pageEcon();return`<h1>시장</h1>${mkTabs()}<input placeholder="종목명 또는 티커 검색 (예: 삼성, NVDA)" oninput="q=this.value;list()" value="${q}"><div class="sub" style="margin:10px 2px">USD/KRW ${FX.toFixed(2)} · 가격은 시뮬레이션 데이터입니다</div><div class="card" id="ml"></div>`},
portfolio(){const T=total(),by={'현금':S.cash};Object.entries(S.hold).forEach(([id,h])=>{const k=KIND[A(id).k];by[k]=(by[k]||0)+h.q*price(id)});S.bank.forEach(b=>{const k=b.ty==='dep'?'예금':'적금';by[k]=(by[k]||0)+bankPrin(b)});
 const sh=['#111','#444','#777','#999','#bbb','#d4d4d4','#e8e8e8'],e=Object.entries(by).sort((a,b)=>b[1]-a[1]);const pl=holdVal()-cost();
 return`<h1>포트폴리오</h1><div class="big">${won(T)}</div><div style="margin:16px 0">${donut(e.map(([k,v],i)=>({k,v,c:`color-mix(in srgb,var(--ink) ${Math.max(14,100-i*15)}%,var(--bg))`})))}</div>
 <div class="card">${e.map(([k,v])=>`<div class="row tap" onclick="pfk=pfk==='${k}'?'':'${k}';render()"><span style="${pfk===k?'font-weight:700':''}">${k}</span><span><b>${won(v)}</b> <span class="sub">${(v/T*100).toFixed(1)}%</span></span></div>`).join('')}</div>
 ${planView(by,T)}<div class="lab">보유 종목${pfk?' · '+pfk:''}</div><div class="card">${Object.entries(S.hold).filter(([id])=>!pfk||KIND[A(id).k]===pfk).map(([id,h])=>{const a=A(id),r=(a.p/h.c-1)*100;return`<div class="row tap" onclick="openDetail('${id}')"><div><b>${a.n}</b><div class="sub">${+h.q.toFixed(4)}개 · 평단 ${won(h.c)}</div></div><div style="text-align:right"><b>${won(h.q*a.p)}</b><div class="${cl(r)}" style="font-size:13px">${sg((a.p-h.c)*h.q)} (${pc(r)})</div></div></div>`}).join('')||'<div class="sub">보유 종목이 없습니다. 시장에서 매수해보세요.</div>'}</div>
 <div class="lab">손익</div><div class="grid g2"><div class="card stat"><div class="sub">미실현손익</div><div class="v ${cl(pl)}">${sg(pl)}</div></div><div class="card stat"><div class="sub">실현손익</div><div class="v ${cl(S.realized)}">${sg(S.realized)}</div></div></div>`},
tx(){const F=[['all','전체'],['study','공부급여'],['bank','예금·적금'],['interest','이자'],['kr','주식'],['etf','ETF'],['gold','금'],['coin','코인']];
 const rows=S.tx.filter(t=>flt==='all'||t.ty===flt||(flt==='kr'&&t.ty==='us'));
 return`<h1>거래내역</h1><div class="seg" style="overflow:auto">${F.map(([k,l])=>`<button class="${flt===k?'on':''}" onclick="flt='${k}';render()">${l}</button>`).join('')}</div><div class="card">${rows.map(t=>`<div class="row"><div><b>${t.m}</b><div class="sub">${new Date(t.t).toLocaleDateString('ko-KR')}</div></div><b class="${cl(t.a)}">${sg(t.a)}</b></div>`).join('')||'<div class="sub">내역이 없습니다</div>'}</div>`},
more(){const st=ST();return`<h1>더보기</h1>${ntView()}${bankView()}${monthView()}${achView()}<div class="lab">설정</div><div class="card"><div class="sub">시간당 급여 (원)</div><input type="number" value="${S.wage}" onchange="S.wage=+this.value||0;save();toast('저장됨')"><div class="sub" style="margin-top:14px">거래 수수료 (%)</div><input type="number" step=".001" value="${S.fee*100}" onchange="S.fee=(+this.value||0)/100;save();toast('저장됨')"><div class="sub" style="margin-top:14px">공부 보너스 (하루 N시간 이상 : 추가 %)</div><div class="sub">${S.tiers.map(([h,r])=>h+'h+ → '+r*100+'%').join(' · ')}</div></div>
 <div class="lab">실시간 시세</div><div class="card"><div class="sub">프록시 URL (Cloudflare Worker 주소)</div><input value="${API}" placeholder="https://xxx.workers.dev" onchange="localStorage.setItem('si-api',this.value.trim());location.reload()"><div class="sub" style="margin-top:10px">상태: ${APIST}${KRST?' · '+KRST:''}${NREAL?' · 뉴스 연결':''} · 비트코인·이더리움은 Binance 실시간 연결</div></div><div class="lab">게임</div><div class="card tap" onclick="tab='game';render();scrollTo(0,0)"><b>미니게임</b><div class="sub">게임머니로만 즐기는 가상 게임 · 실제 자산과 분리</div></div><div class="lab">화면</div><div class="seg">${[['','시스템'],['light','라이트'],['dark','다크']].map(([k,l])=>`<button class="${S.theme===k?'on':''}" onclick="S.theme='${k}';theme();save();render()">${l}</button>`).join('')}</div>
 ${statsView()}<button class="btn w" style="margin-top:22px" onclick="newSim()">새 시뮬레이션 시작 (자산 배분 설정)</button><button class="btn s w" style="margin-top:10px" onclick="if(confirm('모든 기록을 지우고 데모 데이터로 초기화할까요?')){S=demo();save();render()}">시뮬레이션 초기화</button>`}};
let ctype='l',ma=false,smo=0,sp=30,pfk='',gbet=10000,gres='',gcoin='h',gdice=3,grl='r',mt='stocks',nc='전체',q='',flt='all',CHD=[],CHL=[],CHF=n=>won(n),dsel=null,dper=30,ft='is',fp='y';
